aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      apps.tanzu.vmware.com/aggregate-to-workload: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-task
rules:
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  - deletecollection