apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-credentials
type: Opaque
stringData:
  sonar_login: admin
  sonar_password: 'VMware1!'
  ## http with 80 only. https is planned.
  sonar_host_url: 'http://sonar-server80.h2o-2-22280.h2o.vmware.com'
  sonar_token: ''
  # caFile: |
  #   CADATA