apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-credentials
type: Opaque
stringData:
  sonar_login: admin
  sonar_password: 'VMware1!'
  ## http with 80 only. https is planned.
  #sonar_host_url: 'http://sonar-server80.h2o-2-22280.h2o.vmware.com'
  sonar_host_url: 'https://sonar-server.h2o-2-22280.h2o.vmware.com'
  sonar_token: ''
  ## sonar_ca_crt:  optional if sonar_host_url is on SSL
  ## fetch sonaqube server CA from view cluster: kubectl get secrets -n sonarqube sonar-default-tls -o jsonpath='{.data.ca\.crt}' | base64 -d
  # sonar_ca_crt: | 
  #   -----BEGIN CERTIFICATE-----
  #  ...
  #   -----END CERTIFICATE-----
