apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/use-sonarqube: "true"  # added this as a scanner task selector
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
 # serviceAccountName: #@ data.values.service_account_name
  source:
    git:
      url: https://github.com/myminseok/tanzu-java-web-app
      ref:
        branch: main
  params:
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap/scc-ootb-supply-chain-testing.html multiple testing pipeline
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java

  ## use secrets instead( will be injected into tasks.yml)
  # - name: sonar_host_url
  #   value: 'http://sonar-server80.h2o-2-22280.h2o.vmware.com'
  # - name: sonar_password
  #   value: ''
  # - name : sonar_token
  #   value: ''
  # - name: buildServiceBindings
  #   value:
  #   - kind: Secret
  #     name: workload-custom-ca