apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tanzu-java-web-app-ingress
  annotations:
    ako.vmware.com/enable-tls: "true"
#  labels:
#    loadbalancer: run-1-glsb-dev
spec:
#  ingressClassName: avi-lb
  tls:
  - hosts: 
    - myapp.apps.tap.lab.pcfdemo.net
    secretName: app-tls-secret
  rules:
    - host: myapp.apps.tap.lab.pcfdemo.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tanzu-java-web-app
              port:
                number: 8080
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
   name: selfsigned-issuer
   namespace: my-space
spec:
   selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
   name: app-domain-selfsigned-certificate
   namespace: my-space
spec:
   commonName: "*.apps.tap.lab.pcfdemo.net"
   dnsNames:
     - "*.apps.tap.lab.pcfdemo.net"
   issuerRef:
     name: selfsigned-issuer
   privateKey:
     algorithm: RSA
   secretName: app-tls-secret
   usages:
   - server auth
   - client auth
