#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: others-secret-from-nsp-gitops
  annotations:
    tekton.dev/git-0: gitlab.lab.pcfdemo.net
type: kubernetes.io/basic-auth
stringData:
  username: xx
  password: xx
