#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all
---
#@overlay/match missing_ok=True
profile: iterate # Can take iterate, build, run, view.

#@overlay/match missing_ok=True
supply_chain: testing_scanning # Can take testing, testing_scanning.

#@overlay/match missing_ok=True
ootb_supply_chain_testing: # Optional if the corresponding shared keys are provided.
  registry:
    server: "BUILDSERVICE_REGISTRY_HOSTNAME"
    repository: "SUPPLYCHAIN_REPO"
  gitops:
    ssh_secret: "" # (Optional) Defaults to "".

#@overlay/match missing_ok=True
ootb_supply_chain_testing_scanning: # Optional if the corresponding shared keys are provided.
  registry:
    server: "BUILDSERVICE_REGISTRY_HOSTNAME"
    repository: "SUPPLYCHAIN_REPO"
    ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-scc-gitops-vs-regops.html
  gitops:
    ssh_secret: git-ssh
    server_address: https://github.com
    repository_owner: SUPPLYCHAIN_GITOPS_REPOSITORY_OWNER
    repository_name: tap-gitops-repo
    #branch: main
    commit_strategy: pull_request
    pull_request:
      server_kind: github
      commit_branch: ""
      pull_request_title: ready for review
      pull_request_body: generated by supply chain
      
## https-overlay/apply-cnrs-default-tls-run-cluster.sh
#@overlay/match missing_ok=True
cnrs:
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  #@overlay/match missing_ok=True
  default_tls_secret: tanzu-system-ingress/cnrs-default-tls
