#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all
---
#@overlay/match missing_ok=True
profile: iterate # Can take iterate, build, run, view.

#@overlay/match missing_ok=True
supply_chain: testing_scanning # Can take testing, testing_scanning.

#@overlay/match missing_ok=True
ootb_supply_chain_testing: # Optional if the corresponding shared keys are provided.
  registry:
    server: "BUILDSERVICE_REGISTRY_HOSTNAME"
    repository: "SUPPLYCHAIN_REPO"
  # gitops:
  #   ssh_secret: "" # (Optional) Defaults to "".
  gitops:
    server_address: https://github.com/ ## This must include the scheme/protocol (e.g. https:// or ssh://)
    #server_address: ssh://git@github.com/
    repository_owner: SUPPLYCHAIN_GITOPS_REPOSITORY_OWNER
    username: SUPPLYCHAIN_GITOPS_REPOSITORY_OWNER
    repository_name: SUPPLYCHAIN_GITOPS_REPOSITORY_NAME
    #branch: main
    ssh_secret: gitops-basic
    commit_strategy: direct #direct,pull_request
  cluster_builder: default
  service_account: default

#@overlay/match missing_ok=True
ootb_supply_chain_testing_scanning: # Optional if the corresponding shared keys are provided.
  registry:
    server: "BUILDSERVICE_REGISTRY_HOSTNAME"
    repository: "SUPPLYCHAIN_REPO"
    ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-scc-gitops-vs-regops.html
  gitops:
    ssh_secret: gitops-basic
    server_address: https://github.com
    repository_owner: SUPPLYCHAIN_GITOPS_REPOSITORY_OWNER
    repository_name: SUPPLYCHAIN_GITOPS_REPOSITORY_NAME
    #branch: main
    commit_strategy: pull_request
    pull_request:
      server_kind: github
      commit_branch: ""
      pull_request_title: ready for review
      pull_request_body: generated by supply chain
      
## https-overlay/apply-cnrs-default-tls-run-cluster.sh
#@overlay/match missing_ok=True
cnrs:
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  default_tls_secret: tanzu-system-ingress/cnrs-default-tls
  ingress:
    external:
      namespace: tanzu-system-ingress

#@overlay/match missing_ok=True
namespace_provisioner:
  controller: true
  default_parameters:
    supply_chain_service_account:
      secrets:
      - gitops-basic
      - gitops-ssh
  # overlay_secrets:
  # - name: namespace-provisioner-overlay-add-secrets-to-sa
  #   namespace: tap-install
  #   create_export: true

#@overlay/match missing_ok=True
package_overlays:
- name: cnrs
  secrets:
  - name: cnrs-default-tls-overlay
  # ## for pvc support on knative.
  # - name: "knative-serving-overlay"

  
excluded_packages:
- policy.apps.tanzu.vmware.com # workaround for policy controller error
# - api-portal.tanzu.vmware.com
# - learningcenter.tanzu.vmware.com
# - workshops.learningcenter.tanzu.vmware.com
# - tap-telemetry.tanzu.vmware.com
# - sso.apps.tanzu.vmware.com

