apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: node-http
  labels:
    app.kubernetes.io/part-of: node-http
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: external-deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: node-http
    carto.run/workload-namespace: my-space
spec:
  source:
    image: ghcr.io/myminseok/tap-service/minseok-supply-chain/node-http-my-space-bundle:41b79c9e-9caa-46a1-8bd3-02cb2f37868c
