shared:
  ingress_domain: "TAP_DOMAIN"
  image_registry:
    project_path: "IMGPKG_REGISTRY_HOSTNAME/IMGPKG_REPO"
    username: "IMGPKG_REGISTRY_USERNAME"
    password: "IMGPKG_REGISTRY_PASSWORD"
  kubernetes_distribution: "" # To be passed only for OpenShift. Defaults to "".
  ca_cert_data: | # To be passed if using custom certificates.
    -----BEGIN CERTIFICATE-----
    MIID5TCCAs2gAwIBAgIJAMWKW6niC9SnMA0GCSqGSIb3DQEBCwUAMA8xDTALBgNV
    BAMMBG15Y2EwIBcNMjIxMTE3MTIzMjQxWhgPMjA1MDA0MDQxMjMyNDFaMG4xCzAJ
    BgNVBAYTAktPMQ4wDAYDVQQIDAVTZW91bDEOMAwGA1UEBwwFU2VvdWwxDDAKBgNV
    BAoMA09yZzENMAsGA1UECwwEdW5pdDEiMCAGA1UEAwwZaDJvLTItMjI1Ny5oMm8u
    dm13YXJlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALEA9lKs
    AuH2fktSfUvrpMfh8quStkm8wqfumRlVj0tMhs3M7tMlUl4e5bfi5gNTxoEchawG
    jE4FWKo19XccG2uaudr43ioPd/xJmLD9RBrOIcuoiaYAZGzOLQ1rqbbRdCxSy66D
    BGxQCvudW1rAqJhaYNsUBKDQEKfO3PCZOiZ9DyISheR7gU4b+/MzXJ+m/BIEPjHK
    e3ver+mtotiRuIIM2FjgDSUUGksmI/bHkLAOUFwjaVhB97IpgW/gQ9L2LP3tUuyF
    CJEuPS08Dqobl5xXeoYyKoUrYE3OKVS+ytVB50hG/EYvRc7rKZnv6SQGCbrImAjj
    ttd+xJRdS4KVh0ECAwEAAaOB4jCB3zBKBgNVHSMEQzBBgBRgMkpJhBLDu2NuK+sy
    fJpV93zrtqETpBEwDzENMAsGA1UEAwwEbXljYYIUO/QfKBRofjgd//5sGBVnKtCC
    z8owCQYDVR0TBAIwADALBgNVHQ8EBAMCBDAwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
    CCsGAQUFBwMCMFoGA1UdEQRTMFGCGyouaDJvLTItMjI1Ny5oMm8udm13YXJlLmNv
    bYIgaGFyYm9yLmgyby0yLTIyNTcuaDJvLnZtd2FyZS5jb22HBH8AAAGHBKwRAAGH
    BArcD1owDQYJKoZIhvcNAQELBQADggEBAFl0DquGwU7GngqC9z7t9JZMWBC7g9WV
    DYXp2R+WlUZ8/I4GgqBnCbVSTz+A7nyWInbkJfS23ej0mcjpZuTRRlgKGu2He1T/
    0Hu2cJ03BCsbB/wLSGgJyGWiSub12jqKoyRFD4qlkU+ddxxPZo8GEpuSUz3DlkdT
    TcUTr1zC91+yMXogSlx5Ztl+hQQQzjk31H3eAWaU7WEEuaDkyBY5FtJe5z2daShH
    x6RtTZzJ/pp6pe9uI1Gln8xjSNcArkNvX1LnIMM3JdLj6pJ9NtrghSULXfHYWheF
    rRZzPSE77bClb/6uGbqA2uIPxI66dZhwgYxt2PlNCv1jzeHxn3U7VVw=
    -----END CERTIFICATE-----
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

#The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

#Below are the keys which may have default values set, but can be overridden.

profile: full # Can take iterate, build, run, view.
supply_chain: basic            # Can take testing, testing_scanning.
#supply_chain: testing          # Can take testing, testing_scanning.
## TODO 2nd tap update
#supply_chain: testing_scanning # Can take testing, testing_scanning.

ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: "BUILDSERVICE_REGISTRY_HOSTNAME" # Takes the value from shared section above by default, but can be overridden by setting a different value.
    repository: "SUPPLYCHAIN_REPO" # Takes the value from shared section above by default, but can be overridden by setting a different value.
  gitops:
    ssh_secret: "" # Takes "" as value by default; but can be overridden by setting a different value.

contour:
  envoy:
    service:
      type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

buildservice:
  kp_default_repository: "BUILDSERVICE_REGISTRY_HOSTNAME/BUILDSERVICE_REPO"
  kp_default_repository_username: "BUILDSERVICE_REGISTRY_USERNAME"
  kp_default_repository_password: "BUILDSERVICE_REGISTRY_PASSWORD"
  stack_configuration: jammy-only
  ## for airgapped env, it requires to exclude dependencies from buildservice at first, to install tbs-full-deps later.
  exclude_dependencies: true


tap_gui:
  service_type: ClusterIP # If the shared.ingress_domain is set as above, this must be set to ClusterIP
  app_config:
    customize:
      custom_name: "Developer Portal"
    organization:
      name: "DevOps Team"
    proxy:
      /metadata-store:
        target: https://metadata-store-app.metadata-store:8443/api/v1
        changeOrigin: true
        secure: false
    catalog:
      locations:
        - type: url
          target: https://github.com/myminseok/tap-catalog/blob/main/blank/catalog-info.yaml
        - type: url
          target: https://github.com/myminseok/tap-catalog/blob/main/yelb/yelb-catalog/catalog-info.yaml
        # - type: url
        #   target: https://github.com/dbha/myrsvpapp/blob/main/rsvpapp-catalog/catalog-info.yaml
        # - type: url
        #   target: https://github.com/dbha/spring-sensors/blob/main/catalog-info.yaml
        # - type: url
        #   target: https://github.com/dbha/tap-catalog/blob/main/catalog-info.yaml

    # github working
    # auth:
    #   environment: development
    #   providers:
    #     github:
    #       development:
    #         clientId: 
    #         clientSecret: 


## package scanning.apps.tanzu.vmware.com 
## deployment.apps/scan-link-controller-manager > Could not find CA in Secret","err":"unable to set up connection to Supply Chain Security Tools - Store"
## kubectl rollout restart deployment.apps/scan-link-controller-manager -n scan-link-system
scanning:
  metadataStore:
    url: "" # Configuration is moved, so set this string to empty.

cnrs:
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

metadata_store:
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-scst-scan-upgrading.html
  ns_for_export_app_cert: "*"
  app_service_type: LoadBalancer
  #app_service_type: ClusterIP

api_portal:
  apiPortalServer:
    title: "API portal"
    description: "Description"
    # imagePullPolicy: IfNotPresent
    # registryCredentialsSecret: api-portal-image-pull-secret
    replicaCount: 1
    sourceUrls: "https://petstore.swagger.io/v2/swagger.json,https://petstore3.swagger.io/api/v3/openapi.json,http://myweb.lab.pksdemo.net:8080/openapi.json,http://myweb.lab.pksdemo.net:9090/v3/api-docs"
    sourceUrlsCacheTtlSec: "10"
    sourceUrlsTimeoutSec: "10"
    requestMemory: "512Mi"
    requestCpu: "100m"
    limitMemory: "1024Mi"
    limitCpu: "500m"
    namespace: "api-portal"
    trustInsecureSourceUrls: true
    caCertData: ""

  sso:
    enabled: false
    # secretName: sso-credentials

## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-app-live-view-install.html
appliveview:
  backend:
    ingressEnabled: true

excluded_packages:
- policy.apps.tanzu.vmware.com # workaround for policy controller error
