## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-multicluster-reference-tap-values-run-sample.html
profile: run # Can take iterate, build, run, view.
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

shared:
  ingress_domain: "TAP_DOMAIN"
  image_registry:
    project_path: "IMGPKG_REGISTRY_HOSTNAME/IMGPKG_REPO"
    username: "IMGPKG_REGISTRY_USERNAME"
    password: "IMGPKG_REGISTRY_PASSWORD"
  kubernetes_distribution: "" # To be passed only for OpenShift. Defaults to "".
  #ca_cert_data: | # it will be injected by scripts if IMGPKG_REGISTRY_CA_CERTIFICATE is defined as ENV

buildservice:
  kp_default_repository: "BUILDSERVICE_REGISTRY_HOSTNAME/BUILDSERVICE_REPO"
  kp_default_repository_username: "BUILDSERVICE_REGISTRY_USERNAME"
  kp_default_repository_password: "BUILDSERVICE_REGISTRY_PASSWORD"
  stack_configuration: jammy-only
  ## for airgapped env, it requires to exclude dependencies from buildservice at first, to install tbs-full-deps later.
  exclude_dependencies: true

supply_chain: basic            # Can take testing, testing_scanning.

contour:
  envoy:
    service:
      type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

excluded_packages:
- policy.apps.tanzu.vmware.com # workaround for policy controller error
