apiVersion: v1
kind: Secret
metadata:
  name: maven-settings
type: service.binding/maven
stringData:
  type: maven
  provider: sample
  settings.xml: |
    <settings>
      <mirrors>
        <mirror>
          <id>my-mirror</id>
          <name>My Mirror Repository</name>
          <url>https://192.168.0.6:9443/nexus/content/repositories/central/</url>
          <mirrorOf>external:*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
