apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: demo-corp
  description: The demo-corp organization
  links:
    - url: http://www.backstage.io/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Demo Corp
    email: demo@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [it]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-group
  description: A Backstage example group
spec:
  targets:
    - ./it-dept.yaml
    - ./dev-dept.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
