apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  creationTimestamp: "2022-11-30T08:24:08Z"
  generation: 1
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: tanzu-java-web-app
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: tanzu-java-web-app
    carto.run/workload-namespace: my-space2
  name: tanzu-java-web-app
  namespace: my-space2
  resourceVersion: "2237539"
  uid: 5d503626-744b-4568-b2cd-44f80da4e545
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  source:
    git:
      ref:
        branch: main
      url: https://github.com/myminseok/tap-gitops-repo.git
    subPath: config/my-space/tanzu-java-web-app
