#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ registry_secret_name = "grafana-reg-creds"

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ registry_secret_name
  namespace: #@ data.values.namespace
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name":"grafana"}})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
        - name: #@ registry_secret_name
          