apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: true
  annotations:
    autoscaling.knative.dev/minScale: "2" ## should be greater than 2 to create PDB, if less than 2 or empty, then PDB will be removed if exists.
spec:
  source:
    git:
      url: https://github.com/myminseok/tanzu-java-web-app
      ref:
        branch: main
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: pdb_maxUnavailable
    value: 50%    ## set any value as string. default is 1 if empty.
  # - name: pdb_minAvailable
  #   value: 50%     ## set any value as string. if pdb_minAvailable is set, then pdb_maxUnavailable is ignored.
