profile: full
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

shared:
  ingress_domain: "TAP_DOMAIN"
  image_registry:
    project_path: "IMGPKG_REGISTRY_HOSTNAME/IMGPKG_REPO"
    secret:
      name: "registry-credentials" ## will be created by "05-prepare-resources-for-tap.sh"
      namespace: "tap-install"
  kubernetes_distribution: "" # To be passed only for OpenShift. Defaults to "".
  #ca_cert_data: | # it will be injected by scripts if IMGPKG_REGISTRY_CA_CERTIFICATE is defined as ENV

supply_chain: basic       # Can take testing, testing_scanning.
#supply_chain: testing          # Can take testing, testing_scanning.
## TODO 2nd tap update
#supply_chain: testing_scanning # Can take testing, testing_scanning.

ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: "BUILDSERVICE_REGISTRY_HOSTNAME" # Takes the value from shared section above by default, but can be overridden by setting a different value.
    ## Takes the value from shared section above by default, but can be overridden by setting a different value.
    ## will be created after the initial workload has been built successfully.
    repository: "SUPPLYCHAIN_REPO" 

  gitops:
    ssh_secret: "" # Takes "" as value by default; but can be overridden by setting a different value.

contour:
  envoy:
    service:
      type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

buildservice:
  ## it  will be created after build-service is installed(rerun 04-relocate-images-tbs-full-deps.sh, 31-setup-repository-tbs-full-deps.sh 
  kp_default_repository: "BUILDSERVICE_OWNER_REPOSITORY/BUILDSERVICE_REPO"
  ## TODO apply kp-default-repo-secret
  kp_default_repository_username: "BUILDSERVICE_REGISTRY_USERNAME"
  kp_default_repository_password: "BUILDSERVICE_REGISTRY_PASSWORD"
  # kp_default_repository_secret: # Takes the value from the shared section by default, but can be overridden by setting a different value.
  #   name: "kp-default-repo-secret"
  #   namespace: "build-service"
  stack_configuration: jammy-only
  ## for airgapped env, it requires to exclude dependencies from buildservice at first, to install tbs-full-deps later.
  exclude_dependencies: true

tap_gui:
  service_type: ClusterIP # If the shared.ingress_domain is set as above, this must be set to ClusterIP
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/tap-gui-plugins-scc-tap-gui.html
  metadataStoreAutoconfiguration: true 
  app_config:
    customize:
      custom_name: "Developer Portal"
    organization:
      name: "DevOps Team"
    catalog:
      locations:
        - type: url
          target: https://github.com/myminseok/tap-catalog/blob/main/blank/catalog-info.yaml
        - type: url
          target: https://github.com/myminseok/tap-catalog/blob/main/yelb/yelb-catalog/catalog-info.yaml
        # - type: url
        #   target: https://github.com/dbha/myrsvpapp/blob/main/rsvpapp-catalog/catalog-info.yaml
        # - type: url
        #   target: https://github.com/dbha/spring-sensors/blob/main/catalog-info.yaml
        # - type: url
        #   target: https://github.com/dbha/tap-catalog/blob/main/catalog-info.yaml

    ## github integration
    # auth:
    #   environment: development
    #   providers:
    #     github:
    #       development:
    #         clientId: 
    #         clientSecret: 


## package scanning.apps.tanzu.vmware.com 
## deployment.apps/scan-link-controller-manager > Could not find CA in Secret","err":"unable to set up connection to Supply Chain Security Tools - Store"
## kubectl rollout restart deployment.apps/scan-link-controller-manager -n scan-link-system
scanning:
  # metadataStore:
  #   url: "" # Configuration is moved, so set this string to empty. it works for full cluster, on tap 1.5
  metadataStore: {} # Deactivate Supply Chain Security Tools - Store integration 
  
cnrs:
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

metadata_store:
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-scst-scan-upgrading.html
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/scst-scan-upgrading.html
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/install-offline-profile.html#full-profile-3
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP. it works for full cluster on tap 1.5
  #app_service_type: LoadBalancer ## it works for full cluster on tap 1.5

## api_portal will be comment out here due to following error and will be installed while updating tap
## error while installation.
## kapp: Error: Expected to find kind 'projectcontour.io/v1/HTTPProxy', but did not:
##    - Kubernetes API server did not have matching apiVersion + kind
##    - No matching CRD was found in given configuration
# api_portal:
#   apiPortalServer:
#     title: "API portal"
#     description: "Description"
#     # imagePullPolicy: IfNotPresent
#     # registryCredentialsSecret: api-portal-image-pull-secret
#     replicaCount: 1
#     sourceUrls: "https://petstore.swagger.io/v2/swagger.json,https://petstore3.swagger.io/api/v3/openapi.json,http://myweb.lab.pksdemo.net:8080/openapi.json,http://myweb.lab.pksdemo.net:9090/v3/api-docs"
#     sourceUrlsCacheTtlSec: "10"
#     sourceUrlsTimeoutSec: "10"
#     requestMemory: "512Mi"
#     requestCpu: "100m"
#     limitMemory: "1024Mi"
#     limitCpu: "500m"
#     namespace: "api-portal"
#     trustInsecureSourceUrls: true
#     caCertData: ""

#   sso:
#     enabled: false
#     # secretName: sso-credentials



## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/app-live-view-install.html
appliveview:
  ingressEnabled: true

## For a single-cluster environment, the Application Live View connector connects to the cluster-local Application Live View back end to register the applications
appliveview_connector:
  backend:
    ingressEnabled: true
    host: appliveview.TAP_DOMAIN
    # sslDeactivated: true
## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/namespace-provisioner-customize-installation.html#con-label-selector
# namespace_provisioner:
#   controller: true
#   namespace_selector:
#     matchExpressions:
#     - key: apps.tanzu.vmware.com/tap-ns
#       operator: Exists
excluded_packages:
- policy.apps.tanzu.vmware.com # workaround for policy controller error
- api-portal.tanzu.vmware.com
- learningcenter.tanzu.vmware.com
- workshops.learningcenter.tanzu.vmware.com
- tap-telemetry.tanzu.vmware.com
- sso.apps.tanzu.vmware.com