apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-http
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-http
    apps.tanzu.vmware.com/has-tests: true
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    subPath: node-http
    git:
      url : https://github.com/myminseok/tanzu-workload-samples
      ### subPath: node-http  ## warning: don't put here, otherwise there will be error
      ref:
        branch: main
  params:
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap/scc-ootb-supply-chain-testing.html multiple testing pipeline
  - name: testing_pipeline_matching_labels
    value:
     # apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: nodejs