---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sonar-selfsigned-issuer
  namespace: sonarqube
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonar-ca
  namespace: sonarqube
spec:
  commonName: sonar-ca
  isCA: true
  issuerRef:
    kind: Issuer
    name: sonar-selfsigned-issuer
  secretName: sonar-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sonar-ca-issuer
  namespace: sonarqube
spec:
  ca:
    secretName: sonar-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonar-default-tls
  namespace: sonarqube
spec:
  dnsNames:
  - sonar-server.h2o-2-22280.h2o.vmware.com ## TODO
  issuerRef:
    kind: Issuer
    name: sonar-ca-issuer
  secretName: sonar-default-tls
