apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonarqube-httpproxy-80
  namespace: sonarqube
spec:
  virtualhost:
    fqdn: sonar-server80.h2o-2-22280.h2o.vmware.com ## TODO
  routes:
    - services:
        - name: sonarqube-sonarqube
          port: 9000

