profile: view
ceip_policy_disclosed: true
shared:
  ingress_domain: tap.lab.pcfdemo.net
  image_registry:
    project_path: IMGPKG_REGISTRY_HOSTNAME/tap
    secret:
      name: registry-credentials
      namespace: tap-install
  kubernetes_distribution: ""
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
contour:
  envoy:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.27
tap_gui:
  service_type: ClusterIP
  app_config:
    customize:
      custom_name: Developer Portal
    organization:
      name: DevOps Team
    auth:
      allowGuestAccess: true
      environment: development
      providers:
        github:
          development:
            clientId: xxx
            clientSecret: xxx

    proxy:
      /metadata-store:
        target: https://metadata-store-app.metadata-store:8443/api/v1
        changeOrigin: true
        secure: false
        allowedHeaders:
        - Accept
        - Report-Type-Format
        headers:
          Authorization: Bearer xxxg
          X-Custom-Source: project-star
      /grafana/api:
        target: https://grafana.lab.pcfdemo.net
        headers:
          Authorization: Bearer xxx
    grafana:
      domain: https://grafana.lab.pcfdemo.net
      unifiedAlerting: true
    permission:
      enabled: false
      adminRefs:
      - group:default/editor
      - group:default/viewer
      - group:default/tanzuplatform

    ## gitlab integration(self-signed CA)
    backend:
      reading:
        allow:
        - host: raw.githubusercontent.com
          paths:
          - /myminseok/tap-config-repo-private
        - host: raw.githubusercontent.com
          paths:
          - /myminseok/tap-config-repo-private/main
        - host: gitlab.lab.pcfdemo.net
          paths:
          - /root/tap-catalog-repo
        - host: gitlab.lab.pcfdemo.net
          paths:
          - /root/tap-catalog-repo-private
        - host: gitlab.lab.pcfdemo.net
          paths:
          - /*
    ## gitlab integration(self-signed CA)
    # https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.0/tap.pdf
    # https://backstage.io/docs/features/software-catalog/configuration/#static-location-configuration
    # https://backstage.io/docs/integrations/gitlab/locations
    integrations:
      gitlab:
      - host: gitlab.lab.pcfdemo.net
        token: glpat-xxx
        apiBaseUrl: https://gitlab.lab.pcfdemo.net/api/v4
        baseUrl: https://gitlab.lab.pcfdemo.net
    catalog:
      locations:
      - type: url
        target: https://github.com/myminseok/tanzu-java-web-app/blob/main/config/catalog-tanzu-java-web-app.yml
      - type: url
        target: https://github.com/myminseok/tanzu-java-web-app/blob/main/config/catalog-tanzu-python-web.yml
      - type: url
        target: https://gitlab.lab.pcfdemo.net/root/tap-catalog-repo-private/-/blob/main/catalog-tanzu-java-web-app-private.yml
      - type: url
        target: https://gitlab.lab.pcfdemo.net/root/tap-catalog-repo/-/blob/main/catalog-tanzu-java-web-app-public-gitlab.yml

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
      - type: config
        clusters:
        - url: https://192.168.0.30:6443
          name: build
          authProvider: serviceAccount
          serviceAccountToken: xxx
          skipTLSVerify: true
  metadataStoreAutoconfiguration: false
  tls:
    namespace: tap-gui
    secretName: tap-gui-cert
appliveview:
  ingressEnabled: true

excluded_packages:
- tap-telemetry.tanzu.vmware.com
scanning:
  metadataStore:
    url: ""
api_auto_registration:
  tap_gui_url: https://tap-gui.tap.lab.pcfdemo.net
  cluster_name: view-cluster
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    ...
    4JvkcPoUoY9gpwGYfOd+0Adu5a5mkVTOWRgCZRBpVgjKKGxH9r34x0NHhk97zI2g
    8EeV701AaKCa
    -----END CERTIFICATE-----
accelerator:
  server:
    service_type: ClusterIP
    watched_namespace: accelerator-system
    engine_skip_tls_verify: true
  samples:
    include: true
  sources:
    skip_tls_verify: true
