## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.7/tap/namespace-provisioner-use-case3.html
# Format of the secret that is importable under data.values.imported
apiVersion: v1
kind: Secret
metadata:
  name: user-defined-secrets
  namespace: tap-install
type: Opaque
stringData:
  # Key needs to have .yaml or .yml at the end
  content.yaml: |
    git:
      host: gitlab.lab.pcfdemo.net
      username: value1
      password: value2