#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@overlay/match by=overlay.all
---
#@overlay/match missing_ok=True
package_overlays:
## will be overlayed by scanning-overlay>tap-values-overlay-scanning-ca-overlay.yaml if there is BUILDSERVICE_REGISTRY_CA_CERTIFICATE ENV.
- name: "grype"
  secrets:
  - name: "scanning-ca-overlay"