{
 "title": "Workload5",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Number of Workloads per workload type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(cartographer_workload_info{type=~\".*\"}) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tekton Pipeline Progressing or Failing",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tekton_pipeline_run_status{status!=\"True\", message!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Vulnerability_ Scan - Progressing or Failing",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "scst_image_vulnerability_scan_status{status!=\"True\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Progressing or Failing",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cartographer_workload_status{status!=\"True\", message!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Progressing or Failing",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kpack_build_status{status!=\"True\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Knative Progressing or Failing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "knative_service_status{status!=\"True\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}