## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-multicluster-reference-tap-values-build-sample.html
profile: build # Can take iterate, build, run, view.
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

shared:
  ingress_domain: "TAP_DOMAIN"
  image_registry:
    project_path: "IMGPKG_REGISTRY_HOSTNAME/IMGPKG_REPO"
    secret:
      name: "registry-credentials" ## will be created by 10-prepare-resources-for-tap.sh
      namespace: "tap-install"
  kubernetes_distribution: "" # To be passed only for OpenShift. Defaults to "".
  #ca_cert_data: | # it will be injected by scripts if IMGPKG_REGISTRY_CA_CERTIFICATE is defined as ENV

buildservice:
  ## it  will be created after build-service is installed(rerun 04-relocate-images-tbs-full-deps.sh, 30-prepare-resources-tbs-full-deps.sh, 31-install-tbs-full-deps.sh 
  kp_default_repository: "BUILDSERVICE_REGISTRY_HOSTNAME/BUILDSERVICE_REPO"
  ## TODO apply kp-default-repo-secret
  # kp_default_repository_username: "BUILDSERVICE_REGISTRY_USERNAME"
  # kp_default_repository_password: "BUILDSERVICE_REGISTRY_PASSWORD"
  ## kp_default_repository_secret will be share with buildservice.kp_default_repository_secret in tap-values.yml
  # kp_default_repository_secret: # Takes the value from the shared section by default, but can be overridden by setting a different value.
  #   name: "kp-default-repo-secret"
  #   namespace: "build-service"
  stack_configuration: jammy-only
  ## for airgapped env, it requires to exclude dependencies from buildservice at first, to install tbs-full-deps later.
  exclude_dependencies: true

local_source_proxy:
  repository: "BUILDSERVICE_REGISTRY_HOSTNAME/BUILDSERVICE_REPO/lsp"

supply_chain: basic            # Can take testing, testing_scanning.
ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: "BUILDSERVICE_REGISTRY_HOSTNAME" # Takes the value from shared section above by default, but can be overridden by setting a different value.
    repository: "SUPPLYCHAIN_REPO" # Takes the value from shared section above by default, but can be overridden by setting a different value.
  gitops:
    ssh_secret: "" # Takes "" as value by default; but can be overridden by setting a different value.

## package scanning.apps.tanzu.vmware.com 
## deployment.apps/scan-link-controller-manager > Could not find CA in Secret","err":"unable to set up connection to Supply Chain Security Tools - Store"
## kubectl rollout restart deployment.apps/scan-link-controller-manager -n scan-link-system
scanning:
  # metadataStore:
  #   url: "" # Configuration is moved, so set this string to empty. it works for full cluster, on tap 1.5
  metadataStore: {} # Deactivate Supply Chain Security Tools - Store integration 

contour:
  envoy:
    service:
      type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

# https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/app-live-view-troubleshooting.html#no-live-info
# connector should be able to connect to appliveview.TAP_DOMAIN
# on view cluster:  k get secret -n app-live-view appliveview-cert -o yaml -ojsonpath='{.data.ca\.crt}' | base64 -d
# kubectl -n app-live-view-connector delete pods -l=name=application-live-view-connector
appliveview_connector:
  backend:
    sslDisabled: false
    sslDeactivated: false
    ingressEnabled: true
    host: appliveview.TAP_DOMAIN
    #host: appliveview.tap.lab.pcfdemo.net
    caCertData: |-
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
  activateSensitiveOperations: true
  
excluded_packages:
- policy.apps.tanzu.vmware.com # workaround for policy controller error
