apiVersion: v1
kind: Secret
metadata:
  name: ootb-templates-overlay
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tap/package-overlays
stringData:
  ootb-templates-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"apiVersion": "carto.run/v1alpha1", "kind": "ClusterTemplate","metadata":{"name":"config-writer-template"}}), expects="0+"
    ---
    #@overlay/replace
    kind: ClusterConfigTemplate
    spec:
      #@overlay/match missing_ok=True
      configPath: .spec.inputs.params
      #@overlay/match missing_ok=True
      lifecycle: immutable