# rabbitmqcluster-clusterinstanceclass.yaml
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: rabbitmq
spec:
  description:
    short: It's a RabbitMQ cluster!
  pool:
    group: rabbitmq.com
    kind: RabbitmqCluster
# for Postgres
#   group: sql.tanzu.vmware.com
#   kind: Postgres
# for MySql
#   group: with.sql.tanzu.vmware.com
#   kind: MySQL
