apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tap-wildcard-cert
  namespace: tap-gui
spec:
  delegations:
  - secretName: tap-wildcard-cert
    targetNamespaces:
    - "*"