apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tap-ingress-selfsigned-bootstrap
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-ingress-selfsigned-root-ca
  namespace: cert-manager
spec:
  commonName: tap-ingress-selfsigned-root-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: tap-ingress-selfsigned-bootstrap
  secretName: tap-ingress-selfsigned-root-ca

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tap-ingress-selfsigned
spec:
  ca:
    secretName: tap-ingress-selfsigned-root-ca
