profile: run
ceip_policy_disclosed: true
shared:
  ingress_domain: tap.lab.pcfdemo.net
  image_registry:
    project_path: IMGPKG_REGISTRY_HOSTNAME/tap
    secret:
      name: registry-credentials
      namespace: tap-install
  kubernetes_distribution: ""
contour:
  envoy:
    service:
      type: LoadBalancer
# https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/app-live-view-troubleshooting.html#no-live-info
# connector should be able to connect to appliveview.TAP_DOMAIN
# on view cluster:  k get secret -n app-live-view appliveview-cert -o yaml -ojsonpath='{.data.ca\.crt}' | base64 -d
## k get  secrets -n tap-gui tap-wildcard-cert  -o yaml -ojsonpath='{.data.tls\.crt}' | base64 -d
# kubectl -n app-live-view-connector delete pods -l=name=application-live-view-connector
appliveview_connector:
  backend:
    sslDisabled: false
    sslDeactivated: false
    ingressEnabled: true
    host: appliveview.tap.lab.pcfdemo.net
    caCertData: |-
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
  activateSensitiveOperations: true
excluded_packages:
- policy.apps.tanzu.vmware.com
cnrs:
  domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'
  default_tls_secret: tanzu-system-ingress/cnrs-default-tls
package_overlays:
- name: cnrs
  secrets:
  - name: cnrs-default-tls
api_auto_registration:
  tap_gui_url: https://tap-gui.tap.lab.pcfdemo.net
  cluster_name: run-cluster
