apiVersion: v1
kind: Secret
metadata:
  #namespace: tap-namespace-provisioning
  #namespace: my-space-source
  name: gitops-ssh  
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    uiuAHurDeNJxFa/QAAAAAB
    -----END OPENSSH PRIVATE KEY-----
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: xxx
  known_hosts: |
    github.com ssh-rsa 
    
    