apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: my-builder
  namespace: tbs-test 
spec:
  serviceAccountName: default
  tag: harbor.h2o-2-2257.h2o.vmware.com/tap/minseok-tbs-test
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: tanzu-buildpacks/nodejs