apiVersion: v1
kind: Secret
metadata:
  name: namespace-provisioner-overlay-add-secrets-to-sa
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
stringData:
  add-secrets-to-sa-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"apiVersion": "v1", "kind": "ServiceAccount","metadata":{"name":"default"}}), expects="0+"
    ---
    secrets:
    #@overlay/append
    - name: gitops-basic
    - name: gitops-ssh