apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: tanzu-system-ingress
spec:
  delegations:
  - secretName: cnrs-default-tls
    targetNamespaces:
    - "*"