apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: tap-install
spec:
  delegations:
  - secretName: cnrs-default-tls
    targetNamespaces:
    - "*"