apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: true
    # apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      #url: https://github.com/myminseok/tanzu-java-web-app
      url: ssh://git@github.com/myminseok/tanzu-java-web-app.git
      ref:
        branch: main
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap/scc-gitops-vs-regops.html#gitops-workload-parameters-5
  params:
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap/scc-ootb-supply-chain-testing.html multiple testing pipeline
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: java
  - name: gitops_server_address
    value: ssh://git@github.com ## "https://" prefix" is required for basic auth.
  - name: gitops_repository_owner
    value: myminseok
  - name: gitops_repository_name
    value: tap-gitops-repo
  - name: gitops_ssh_secret
    #value: gitops-basic
    value: gitops-ssh
  - name: gitops_branch
    value: main
  - name: api_descriptor
    value:
      type: openapi
      location:
        #baseURL: http://petclinic-hard-coded.my-apps.tapdemo.vmware.com/
        path: "/v3/api-docs"
      owner: team-petclinic
      system: pet-clinics
      description: "A set of API endpoints to manage the resources within the petclinic app.(running on TAP, main)"
