apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: node-express
  labels:
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: external-deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: node-express
    carto.run/workload-namespace: my-space
spec:
  source:
    image: ghcr.io/myminseok/tap-service/minseok-supply-chain/node-express-my-space-bundle:4d17b010-2bbc-4efd-aef1-82e0be791a87
