---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
   name: workload-selfsigned-issuer
   #namespace: my-space
spec:
   selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
   name: workload-selfsigned-certificate
   #namespace: my-space
spec:
   commonName: "*.tap.lab.pcfdemo.net"
   dnsNames:
     - "*.tap.lab.pcfdemo.net"
   issuerRef:
     name: workload-selfsigned-issuer
   privateKey:
     algorithm: RSA
   secretName: workload-tls-secret
   usages:
   - server auth
   - client auth
