apiVersion: v1
kind: Secret
metadata:
  name: knative-cm-config-observability-overlay
  namespace: tap-install
stringData:
  knative-cm-config-observability-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"ConfigMap","metadata":{"name":"config-observability","namespace":"knative-serving"}})
    ---
    data:
      #@overlay/match missing_ok=True
      logging.enable-request-log: "true"
      #@overlay/match missing_ok=True
      logging.request-log-template: '{"FROM_OVERLAY_httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl": "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}", "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent": "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp": "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s", "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'